name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2

      - name: Restore packages
        id: build
        run: npm install

      - name: Build
        id: build
        run: npm run build
